services:
  - type: web
    name: securenote-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000 
      - key: SECRET_TOKEN
        sync: false 